# Site settings
title: Geeks on a Farm 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.geeksonafarm.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "blog/page:num"
team_members:
  - name: Yann Klis
    nickname: yannski
    linkedin: http://www.linkedin.com/in/yannklis
    twitter: https://twitter.com/yannski
  - name: Jean-Christophe Gay
    nickname: jayce
    xing:
    twitter: https://twitter.com/Jc_gay
  - name: Kathleen Fritzsche
    nickname: kathleen_fritzsche
    twitter: https://twitter.com/kathl_fritzsche
    linkedin: https://de.linkedin.com/in/kathleenfritzsche
  - name: Stéphane Becker
    nickname: whirly
    linkedin: https://www.linkedin.com/in/stephanebecker
    twitter: https://twitter.com/whirlyvonelsass
  - name: Christian Atz
    nickname: atz
    linkedin: https://www.linkedin.com/in/christianatz
speakers:
  - name: Jeremy Chatelaine
    title: CEO at Quickmail.io
    bio: "After 10 years in video games and 6 years in finance as a high performer, Jeremy finally built his business in sales acceleration ([Quickmail.io](https://quickmail.io)), where he helps small and medium businesses get more responses from their cold emails while saving them a lot of time in doing so."
    talk_title: The black art of cold emails - Everything you need to know about cold emails to get an avalanche of responses
    talk_description: "More than half a million of automated emails have been sent through my system. I'll let you know what works, and what doesn't work to avoid easy mistakes and start on the right foot. After this workshop, you will have learnt:\n\n* When to use cold emails and when not to\n* What is the most important thing in cold emailing (hint: it's not what you write)\n* Tactics and strategies to get prospects to email\n* The perfect mindset to get a ton of responses from super cold prospects"
    linkedin: https://ch.linkedin.com/in/jeremychatelaine
    twitter: https://twitter.com/jchatelaine
  - name: Yan-Erik Decorde
    title: Change Activator at Programmer la Réussite
    bio: "Yan-Erik is a belief hacker and change activator motivated by evolving towards humanity 4.0. He experienced with the deep reprogramming of human consciousness and culture, from yogic meditation in the Himalayas to neuro linguistic programming and hypnosis, from libertarian transhumanism to generative dialogue and Theory U liberated leaders."
    talk_description: "* The disruption of exponential technologies and the fields ready for entrepreneurial exploitation\n\n* The mindset required to bootstrap an exponential curve\n\n* The secrets of going skunk\n\n* The motivation and flow states to release the human potential."
    linkedin: https://www.linkedin.com/pub/yan-erik-decorde/20/49/854
    twitter: https://twitter.com/yanerikdecorde
  - name: Kathleen Fritzsche
    title: Co-Founder at Accelerate Stuttgart
    bio: "Kathleen attended her first Startup Weekend in 2010 and has been co-organizing and facilitating several events since then. She co-founded StartUp Stuttgart in 2011, the main startup community in Southwest Germany, and Accelerate Stuttgart in 2012. Accelerate Stuttgart is building an accelerator program for startups in Stuttgart and the region. The main goal is to foster and maintain a vibrant startup community in Baden-Württemberg and to help founders to establish their companies."
    talk_title: "Startup community insights - Stuttgart and the region"
    talk_description: "Kathleen will give you some insights into the startup community in Stuttgart and the region, the so-called Neckar Valley. She'll also talk about the success factors of a vibrant community and the advantages and struggles of smaller startup communities."
    twitter: https://twitter.com/kathl_fritzsche
    linkedin: https://de.linkedin.com/in/kathleenfritzsche
  - name: Matthias Hornberger
    title: "VC, CFO at Kizoo"
    bio: "Matthias is CFO of Kizoo. He has been part of the senior management team since the IPO of the AG in 2000. With his long-standing experience in the investment sector and his comprehensive knowledge of typical features of successful business models on the Internet, he is a competent reference person for young founders. Matthias has extensive contacts in the high-tech industry and numerous local and national networks."
    talk_title: "How to pitch a VC"
    talk_description: "As a VC, Matthias is the best person to teach you how to pitch a VC :)"
    linkedin: https://de.linkedin.com/pub/matthias-hornberger/0/184/a51
    twitter: https://twitter.com/mho1960
  - name: Claus-Eckhard Kraemer
    title: "Aichwald Konferenz Organize, Flosoft Co-founder"
    bio: ""
    talk_title: "Communicate or die."
    talk_description: ""
  - name: Thibaut Vincent
    title: Founder of Lemon Factory
    bio: "Thibault is the founder of [Lemon Factory](http://lemonfactory.fr/), a french conversion rate optimization agency. His key areas of expertise are conversion rate optimization, copywriting and website monetization.\n\nHe has written a best-selling book, published by Pearson, on how to make money with a website. And a second one on affiliate marketing. He speaks regularly at events, conferences and business schools (La Sorbonne, Inseec, SEO Camp Day, JCertif, etc.)."
    talk_title: "How to create an high-converting website and double your sales"
    talk_description: "Based on a real use case, Thibaut will walk through all the learnings he's made on funnel optimizations to share his knowledge."
    linkedin: https://www.linkedin.com/pub/thibault-vincent/1a/8a8/29b
    twitter: https://twitter.com/thibaultvincent
  - name: Alexandre Winter
    title: CEO and Founder at Placemeter
    bio: "Before starting Placemeter, Alex was the Co-Founder and CEO of LTU Technologies. He has a PhD in Image Recognition from Telecom Paris, holds 7 patents in the field, and has over 20 years of computer vision expertise in applications ranging from satellite reconnaissance to augmented reality.\n\nPlacemeter made through Techstars 2013 NYC, won WebSummit Alpha Pitch Competition (oct 2013) and raised 3 rounds in the US."
    talk_title: "'If you can make it there, you can make it anywhere' and 'How to pitch, bitch!'"
    talk_description: "How to start and grow your startup in the US; My learnings from pitch bootcamp at Techstars and on stage at [Websummit](http://awinter.me/2014/09/26/websummit-alpha-companies-pitch-till-you-drop/)."
    linkedin: http://www.linkedin.com/pub/alexandre-winter/0/36/409
    twitter: https://twitter.com/awinter
