# Site settings
title: Geeks on a Farm 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.geeksonafarm.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "blog/page:num"
speakers:
  - name: Jeremy Chatelaine
