# Site settings
title: Geeks on a Farm 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.geeks-on-a-farm.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "blog/page:num"
team_members:
  - name: Yann Klis
    nickname: yannski
    linkedin: http://www.linkedin.com/in/yannklis
    twitter: https://twitter.com/yannski
  - name: Jean-Christophe Gay
    nickname: jayce
    xing:
    twitter: https://twitter.com/Jc_gay
  - name: Stéphane Becker
    nickname: whirly
    linkedin: https://www.linkedin.com/in/stephanebecker
    twitter: https://twitter.com/whirlyvonelsass
  - name: Christian Atz
    nickname: atz
    linkedin: https://www.linkedin.com/in/christianatz
speakers:
  - name: Jeremy Chatelaine
    title: CEO at Quickmail.io
    bio: "After 10 years in video games and 6 years in finance as a high performer, he finally built his business in sales acceleration, where he helps small and medium businesses get more responses from their cold emails while saving them a lot of time in doing so."
    talk_title: The black art of cold emails - Everything you need to know about cold emails to get an avalanche of responses
    talk_description: "More than half a million of automated emails have been sent through my system. I'll let you know what works, and what doesn't work to avoid easy mistakes and start on the right foot. After this workshop, you will have learnt:\n\n* When to use cold emails and when not to\n* What is the most important thing in cold emailing (hint: it's not what you write)\n* Tactics and strategies to get prospects to email\n* The perfect mindset to get a ton of responses from super cold prospects"
    linkedin: https://ch.linkedin.com/in/jeremychatelaine
    twitter: https://twitter.com/jchatelaine
  - name: Yan-Erik Decorde
    title: Change Activator at Programmer la Réussite
    bio: "Yan-Erik is a belief hacker and change activator motivated by evolving towards humanity 4.0. He experienced with the deep reprogramming of human consciousness and culture, from yogic meditation in the Himalayas to neuro linguistic programming and hypnosis, from libertarian transhumanism to generative dialogue and Theory U liberated leaders."
    talk_description: "* The disruption of exponential technologies and the fields ready for entrepreneurial exploitation\n\n* The mindset required to bootstrap an exponential curve\n\n* The secrets of going skunk\n\n* The motivation and flow states to release the human potential."
    linkedin: https://www.linkedin.com/pub/yan-erik-decorde/20/49/854
    twitter: https://twitter.com/yanerikdecorde
